# generated by datamodel-codegen:
#   filename:  ai_ingest_job.json

from uuid import UUID

from pydantic import BaseModel, ConfigDict


class Meta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    requestId: str | None = None
    userId: str | None = None
    orgId: str | None = None


class Payload(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    documentId: UUID
    orgId: UUID


class AiIngestJob(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    meta: Meta
    payload: Payload
