# generated by datamodel-codegen:
#   filename:  ai_ingest_summarize_job.json

from uuid import UUID

from pydantic import BaseModel


class Meta(BaseModel):
    requestId: str | None = None
    userId: str | None = None
    orgId: str | None = None


class Payload(BaseModel):
    documentId: UUID
    orgId: UUID


class AiIngestSummarizeJob(BaseModel):
    meta: Meta
    payload: Payload
