# generated by datamodel-codegen:
#   filename:  ai_ingest_job_name.json

from typing import Annotated, Literal

from pydantic import Field

type AiIngestJobName = Annotated[
    Literal["ingest", "summarize"], Field(..., title="AiIngestJobName")
]
