# generated by datamodel-codegen:
#   filename:  queue_setting.json

from pydantic import BaseModel, ConfigDict, Field


class Backoff(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    delay: int | None = None


class KeepJobs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    age: int | None = None
    count: int | None = None


class JobOptions(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    attempts: int
    backoff: Backoff = Field(..., title="Backoff")
    removeOnComplete: bool | int | KeepJobs
    removeOnFail: bool | int | KeepJobs


class QueueSetting(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    prefix: str
    options: JobOptions = Field(..., title="JobOptions")
