# generated by datamodel-codegen:
#   filename:  realtime_message.json

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class RealtimeMessage1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["todos.changed"]


class RealtimeMessage2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["notifications.changed"]


class RealtimeMessage3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["documents.changed"]


class RealtimeMessage4(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["files.changed"]


class RealtimeMessage(
    RootModel[RealtimeMessage1 | RealtimeMessage2 | RealtimeMessage3 | RealtimeMessage4]
):
    root: RealtimeMessage1 | RealtimeMessage2 | RealtimeMessage3 | RealtimeMessage4 = Field(
        ..., title="RealtimeMessage"
    )
