# generated by datamodel-codegen:
#   filename:  realtime_message.json

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field


class TodosChanged(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["todos.changed"]


class NotificationsChanged(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["notifications.changed"]


class DocumentsChanged(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["documents.changed"]


class FilesChanged(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Literal["files.changed"]


type RealtimeMessage = Annotated[
    TodosChanged | NotificationsChanged | DocumentsChanged | FilesChanged,
    Field(..., title="RealtimeMessage"),
]
