# generated by datamodel-codegen:
#   filename:  shared_queue_name.json

from typing import Annotated, Literal

from pydantic import Field

type SharedQueueName = Annotated[Literal["ai-ingest"], Field(..., title="SharedQueueName")]
