# The Gateway API implementation (and the Gateway API CRDs).
addon: envoy-gateway
namespace: envoy-gateway-system
repoURL: registry-1.docker.io/envoyproxy
chart: gateway-helm
version: v1.9.2
wave: "-20"
