/**
 * Client for the Python AI service (apps/ai), generated from its OpenAPI document:
 *
 *   apps/ai/app (Pydantic models) ──(bun run gen)──▶ apps/ai/openapi.json
 *                                 ──(bun run gen)──▶ src/generated (types + zod)
 *
 * Every response is validated against the generated zod schemas, so a contract change
 * on the Python side fails here instead of passing bad data on. Never edit
 * src/generated by hand; CI fails if it's out of date.
 *
 * Each call carries a token signed for that call (60 seconds, AI_SERVICE_SECRET) naming
 * the user and organization it's for: the service trusts nothing else.
 */
import { EventSourceParserStream } from "eventsource-parser/stream";
import { SignJWT } from "jose";
import type * as z from "zod";
import { createClient } from "./generated/client";
import { createDocument, deleteDocument, listDocuments, sentiment } from "./generated/sdk.gen";
import type { AnswerData, ErrorCode, ErrorIssue } from "./generated/types.gen";
import { zAssistantEvent, zErrorResponse } from "./generated/zod.gen";

export type AssistantEvent = z.infer<typeof zAssistantEvent>["event"];

export interface AiCaller {
  userId: string;
  orgId: string;
  requestId?: string | undefined;
}

/**
 * A failure the service reported, with its stable error code, or UPSTREAM_UNAVAILABLE
 * when it couldn't be reached or answered with something other than an error body.
 */
export class AiServiceError extends Error {
  constructor(
    readonly status: number,
    readonly code: ErrorCode,
    readonly params: Record<string, string | number> = {},
    readonly issues: ErrorIssue[] = [],
  ) {
    super(`AI service answered ${status} ${code}`);
  }
}

/** The error a failed response carries, parsed against the service's error model. */
function toServiceError(status: number, body: unknown): AiServiceError {
  const parsed = zErrorResponse.safeParse(body);
  if (!parsed.success) return new AiServiceError(status, "UPSTREAM_UNAVAILABLE");
  const { code, data } = parsed.data;
  return new AiServiceError(status, code, data.params, data.issues ?? []);
}

const TOKEN_LIFETIME_SECONDS = 60;

/** A call's headers: its own token, naming the user and organization, and the request id. */
async function callHeaders(key: Uint8Array, caller: AiCaller) {
  const token = await new SignJWT({ org: caller.orgId })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuer("api")
    .setAudience("ai")
    .setSubject(caller.userId)
    .setIssuedAt()
    .setExpirationTime(`${TOKEN_LIFETIME_SECONDS}s`)
    .sign(key);
  return {
    authorization: `Bearer ${token}`,
    ...(caller.requestId && { "x-request-id": caller.requestId }),
  };
}

/** The result of a call that succeeded; the service's error (or an outage) otherwise. */
async function settle<R extends { error?: unknown; response?: Response }>(
  call: Promise<R>,
): Promise<R> {
  // The generated client never rejects: an unreachable service comes back as a result
  // without a response.
  const result = await call;
  if (!result.response?.ok) throw toServiceError(result.response?.status ?? 503, result.error);
  return result;
}

async function unwrap<T>(call: Promise<{ data?: T; error?: unknown; response?: Response }>) {
  const { data } = await settle(call);
  // The generated client validated the body; one that broke the contract lands here.
  if (data === undefined) throw new AiServiceError(502, "UPSTREAM_UNAVAILABLE");
  return data;
}

export function createAiClient(options: {
  baseUrl: string;
  secret: string;
  timeoutMs?: number;
  /** The longest an answer may stream, start to finish (default two minutes). */
  answerTimeoutMs?: number;
}) {
  const key = new TextEncoder().encode(options.secret);
  const timeoutMs = options.timeoutMs ?? 30_000;

  const headers = (caller: AiCaller) => callHeaders(key, caller);

  /** A client for one call: its token, and a timeout so a hung service can't hang us. */
  async function forCall(caller: AiCaller) {
    return createClient({
      baseUrl: options.baseUrl,
      headers: await headers(caller),
      // Always JSON, so the validator sees every body: left to the content type, a body
      // without one would come back as a raw stream, unchecked.
      parseAs: "json",
      fetch: (input: RequestInfo | URL, init?: RequestInit) =>
        fetch(input, { ...init, signal: AbortSignal.timeout(timeoutMs) }),
    });
  }

  return {
    async sentiment(caller: AiCaller, text: string) {
      return unwrap(sentiment({ client: await forCall(caller), body: { text } }));
    },
    async listDocuments(caller: AiCaller) {
      return unwrap(listDocuments({ client: await forCall(caller) }));
    },
    async createDocument(caller: AiCaller, body: { title: string; content: string }) {
      return unwrap(createDocument({ client: await forCall(caller), body }));
    },
    async deleteDocument(caller: AiCaller, documentId: string) {
      await settle(
        deleteDocument({ client: await forCall(caller), path: { document_id: documentId } }),
      );
    },

    /**
     * Starts an answer. Refusals (budget, feature off, validation) and an unreachable
     * service throw here, before any event; the events that follow are validated against
     * the service's AssistantEvent model.
     */
    async answer(
      caller: AiCaller,
      question: string,
      signal?: AbortSignal,
    ): Promise<AsyncGenerator<AssistantEvent>> {
      // From the service's OpenAPI document: a changed route or body fails to compile. The
      // generated SDK can't be used here: it reads the whole body, and this streams it.
      const path: AnswerData["url"] = "/v1/assistant/answers";
      const body: AnswerData["body"] = { question };
      let response: Response;
      try {
        response = await fetch(new URL(path, options.baseUrl), {
          method: "POST",
          headers: { ...(await headers(caller)), "content-type": "application/json" },
          body: JSON.stringify(body),
          // The caller's signal (the client went away) or the answer's own limit.
          signal: AbortSignal.any([
            AbortSignal.timeout(options.answerTimeoutMs ?? 120_000),
            ...(signal ? [signal] : []),
          ]),
        });
      } catch (cause) {
        throw Object.assign(new AiServiceError(503, "UPSTREAM_UNAVAILABLE"), { cause });
      }
      if (!response.ok || !response.body) {
        throw toServiceError(response.status, await response.json().catch(() => undefined));
      }
      return events(response.body);
    },
  };
}

/** Server-Sent Events from a response body, each one's data one AssistantEvent. */
async function* events(body: ReadableStream<BufferSource>): AsyncGenerator<AssistantEvent> {
  const stream = body
    .pipeThrough(new TextDecoderStream())
    .pipeThrough(new EventSourceParserStream());
  for await (const message of stream) {
    yield zAssistantEvent.parse(JSON.parse(message.data)).event;
  }
}
