/**
 * Client for the Python AI service (apps/ai), generated from its OpenAPI document:
 *
 *   apps/ai/app (Pydantic models) ──(bun run gen)──▶ apps/ai/openapi.json
 *                                 ──(bun run gen)──▶ src/generated (types + zod)
 *
 * Every response is validated against the generated zod schemas, so a contract change
 * on the Python side fails here instead of passing bad data on. Never edit
 * src/generated by hand; CI fails if it's out of date.
 *
 * Each call carries a token signed for that call (60 seconds, AI_SERVICE_SECRET) naming
 * the user and organization it's for: the service trusts nothing else.
 */
import { SignJWT } from "jose";
import type { z } from "zod";
import { createClient } from "./generated/client";
import { createDocument, deleteDocument, listDocuments, sentiment } from "./generated/sdk.gen";
import type { ErrorCode, ErrorIssue } from "./generated/types.gen";
import { zAssistantEvent, zErrorResponse } from "./generated/zod.gen";

export type { DocumentOut as AiDocument, SentimentResponse } from "./generated/types.gen";
export type AssistantEvent = z.infer<typeof zAssistantEvent>["event"];

export interface AiCaller {
  userId: string;
  orgId: string;
  requestId?: string | undefined;
}

/**
 * A failure the service reported, with its stable error code, or UPSTREAM_UNAVAILABLE
 * when it couldn't be reached or answered with something other than an error body.
 */
export class AiServiceError extends Error {
  constructor(
    readonly status: number,
    readonly code: ErrorCode,
    readonly params: Record<string, string | number> = {},
    readonly issues: ErrorIssue[] = [],
  ) {
    super(`AI service answered ${status} ${code}`);
  }
}

/** The error a failed response carries, parsed against the service's error model. */
function toServiceError(status: number, body: unknown): AiServiceError {
  const parsed = zErrorResponse.safeParse(body);
  if (!parsed.success) return new AiServiceError(status, "UPSTREAM_UNAVAILABLE");
  const { code, data } = parsed.data;
  return new AiServiceError(status, code, data.params, data.issues ?? []);
}

const TOKEN_LIFETIME_SECONDS = 60;

export function createAiClient(options: {
  baseUrl: string;
  secret: string;
  timeoutMs?: number;
  /** The longest an answer may stream, start to finish (default two minutes). */
  answerTimeoutMs?: number;
}) {
  const key = new TextEncoder().encode(options.secret);
  const timeoutMs = options.timeoutMs ?? 30_000;

  async function headers(caller: AiCaller) {
    const token = await new SignJWT({ org: caller.orgId })
      .setProtectedHeader({ alg: "HS256" })
      .setIssuer("api")
      .setAudience("ai")
      .setSubject(caller.userId)
      .setIssuedAt()
      .setExpirationTime(`${TOKEN_LIFETIME_SECONDS}s`)
      .sign(key);
    return {
      authorization: `Bearer ${token}`,
      ...(caller.requestId && { "x-request-id": caller.requestId }),
    };
  }

  /** A client for one call: its token, and a timeout so a hung service can't hang us. */
  async function forCall(caller: AiCaller) {
    return createClient({
      baseUrl: options.baseUrl,
      headers: await headers(caller),
      fetch: (input: RequestInfo | URL, init?: RequestInit) =>
        fetch(input, { ...init, signal: AbortSignal.timeout(timeoutMs) }),
    });
  }

  /** The result of a call that succeeded; the service's error (or an outage) otherwise. */
  async function settle<R extends { error?: unknown; response?: Response }>(
    call: Promise<R>,
  ): Promise<R> {
    let result: R;
    try {
      result = await call;
    } catch (cause) {
      throw Object.assign(new AiServiceError(503, "UPSTREAM_UNAVAILABLE"), { cause });
    }
    if (!result.response?.ok) throw toServiceError(result.response?.status ?? 503, result.error);
    return result;
  }

  async function unwrap<T>(call: Promise<{ data?: T; error?: unknown; response?: Response }>) {
    const { data } = await settle(call);
    // The generated client validated the body, so only a response without one lands here.
    if (data === undefined) throw new AiServiceError(502, "UPSTREAM_UNAVAILABLE");
    return data;
  }

  return {
    async sentiment(caller: AiCaller, text: string) {
      return unwrap(sentiment({ client: await forCall(caller), body: { text } }));
    },
    async listDocuments(caller: AiCaller) {
      return unwrap(listDocuments({ client: await forCall(caller) }));
    },
    async createDocument(caller: AiCaller, body: { title: string; content: string }) {
      return unwrap(createDocument({ client: await forCall(caller), body }));
    },
    async deleteDocument(caller: AiCaller, documentId: string) {
      await settle(
        deleteDocument({ client: await forCall(caller), path: { document_id: documentId } }),
      );
    },

    /**
     * Starts an answer. Refusals (budget, feature off, validation) and an unreachable
     * service throw here, before any event; the events that follow are validated against
     * the service's AssistantEvent model.
     */
    async answer(
      caller: AiCaller,
      question: string,
      signal?: AbortSignal,
    ): Promise<AsyncGenerator<AssistantEvent>> {
      let response: Response;
      try {
        response = await fetch(new URL("/v1/assistant/answers", options.baseUrl), {
          method: "POST",
          headers: { ...(await headers(caller)), "content-type": "application/json" },
          body: JSON.stringify({ question }),
          // The caller's signal (the client went away) or the answer's own limit.
          signal: AbortSignal.any([
            AbortSignal.timeout(options.answerTimeoutMs ?? 120_000),
            ...(signal ? [signal] : []),
          ]),
        });
      } catch (cause) {
        throw Object.assign(new AiServiceError(503, "UPSTREAM_UNAVAILABLE"), { cause });
      }
      if (!response.ok || !response.body) {
        throw toServiceError(response.status, await response.json().catch(() => undefined));
      }
      return events(response.body);
    },
  };
}

/** Server-Sent Events from a response body, each `data:` payload one AssistantEvent. */
async function* events(body: ReadableStream<Uint8Array>): AsyncGenerator<AssistantEvent> {
  const decoder = new TextDecoder();
  let buffer = "";
  for await (const chunk of body) {
    buffer += decoder.decode(chunk, { stream: true });
    let end = buffer.indexOf("\n\n");
    while (end !== -1) {
      const frame = buffer.slice(0, end);
      buffer = buffer.slice(end + 2);
      const data = frame
        .split("\n")
        .filter((line) => line.startsWith("data: "))
        .map((line) => line.slice(6))
        .join("\n");
      if (data) yield zAssistantEvent.parse(JSON.parse(data)).event;
      end = buffer.indexOf("\n\n");
    }
  }
}

export type AiClient = ReturnType<typeof createAiClient>;
