/**
 * Writes messages/en.d.json.ts: the English catalog's type with every message as its
 * literal text. TypeScript (with `allowArbitraryExtensions`) reads it instead of the
 * JSON's plain `string`s, so next-intl and use-intl type each message's ICU arguments:
 * `t("email.otp.expires")` without `{minutes}` fails to compile. `bun run gen` keeps it
 * current, and CI's codegen job fails if it drifts.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/** Declares the catalog in `dir`'s en.json, next to it. */
export function declareMessages(dir = join(import.meta.dirname, "..", "messages")) {
  const en: unknown = JSON.parse(readFileSync(join(dir, "en.json"), "utf8"));
  // A JSON object is also a TypeScript type literal, with each string as its literal type.
  writeFileSync(
    join(dir, "en.d.json.ts"),
    `// Generated by scripts/declare-messages.ts from en.json: run \`bun run gen\`.\ndeclare const messages: ${JSON.stringify(en, null, 2)};\nexport default messages;\n`,
  );
}

// Run as `bun scripts/declare-messages.ts`, not when a test imports it.
import.meta.main && declareMessages();
