/**
 * The services' and packages' own scripts, all run by Bun (`bun run gen`, `drift`, the web
 * build, `serve:web`): each writes what it promises, and fails the way it says it does.
 */
import { afterEach, describe, expect, it, mock, spyOn } from "bun:test";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { writeOpenApi } from "../apps/api/scripts/openapi";
import { serveWeb } from "../apps/mobile/scripts/serve-web";
import { copyStatic } from "../apps/web/scripts/copy-static";
import { drift } from "../packages/db/scripts/drift";
import { declareMessages } from "../packages/i18n/scripts/declare-messages";
import { exportSchemas } from "../packages/jobs/scripts/export-schemas";
import { captureOutput } from "./stand-ins";

afterEach(() => mock.restore());

const scratch = () => mkdtempSync(join(tmpdir(), "package-scripts-"));
const read = (path: string) => readFileSync(path, "utf8");

describe("apps/api's OpenAPI document", () => {
  it("is written to the file it's given, for version 1 under /api/v1", async () => {
    const file = join(scratch(), "openapi.json");
    await writeOpenApi(file);
    const spec = JSON.parse(read(file)) as { info: { version: string }; servers: unknown };
    expect(spec.info.version).toBe("1");
    expect(spec.servers).toEqual([{ url: "/api/v1" }]);
    expect(writeOpenApi(undefined)).rejects.toThrow("usage: bun scripts/openapi.ts <file>");
  });
});

describe("apps/web's static assets", () => {
  it("are copied next to the standalone server, with public/ when there is one", () => {
    const dir = scratch();
    mkdirSync(join(dir, ".next/static/chunks"), { recursive: true });
    writeFileSync(join(dir, ".next/static/chunks/app.js"), "app");
    copyStatic(dir);
    const server = join(dir, ".next/standalone/apps/web");
    expect(read(join(server, ".next/static/chunks/app.js"))).toBe("app");
    expect(existsSync(join(server, "public"))).toBe(false);
    mkdirSync(join(dir, "public"));
    writeFileSync(join(dir, "public/sw.js"), "sw");
    copyStatic(dir);
    expect(read(join(server, "public/sw.js"))).toBe("sw");
  });
});

describe("packages/i18n's message types", () => {
  it("declare the English catalog with each message as its literal text", () => {
    const dir = scratch();
    writeFileSync(join(dir, "en.json"), '{"email":{"otp":{"expires":"In {minutes} minutes"}}}');
    declareMessages(dir);
    const declared = read(join(dir, "en.d.json.ts"));
    expect(declared).toStartWith("// Generated by scripts/declare-messages.ts");
    expect(declared).toContain('"expires": "In {minutes} minutes"');
    expect(declared).toEndWith("export default messages;\n");
  });
});

describe("packages/jobs' shared schemas", () => {
  it("write what the Python service is generated from, starting empty", () => {
    const dir = scratch();
    mkdirSync(join(dir, "schemas"));
    writeFileSync(join(dir, "schemas/stale.json"), "{}");
    exportSchemas(dir);
    const schemas = readdirSync(join(dir, "schemas"));
    expect(schemas).not.toContain("stale.json");
    expect(schemas).toEqual(
      expect.arrayContaining(["ai_ingest_ingest_job.json", "error_response.json"]),
    );
    const errorResponse = JSON.parse(read(join(dir, "schemas/error_response.json")));
    expect(errorResponse).toMatchObject({ title: "ErrorResponse" });
    for (const file of ["queue-settings.json", "error-codes.json", "events.json"]) {
      expect(existsSync(join(dir, file))).toBe(true);
    }
    expect(read(join(dir, "realtime-channels.json"))).toContain("{id}");
  });
});

describe("packages/db's drift check", () => {
  /** `prisma migrate diff` answering `outputs` in turn (migrations, then the database). */
  const prisma = (...outputs: { status?: number; stdout?: string }[]) => {
    const calls: string[] = [];
    const spawn = (command: string, args: string[]) => {
      calls.push([command, ...args].join(" "));
      const { status = 0, stdout = "" } = outputs.shift() ?? {};
      return { status, stdout, stderr: status ? "prisma failed\n" : "" };
    };
    return { spawn, calls };
  };
  const written = () => {
    const out = spyOn(process.stdout, "write").mockImplementation(() => true);
    const err = spyOn(process.stderr, "write").mockImplementation(() => true);
    return () => [...out.mock.calls, ...err.mock.calls].map(([text]) => String(text)).join("");
  };

  it("passes when both diffs hold only comments and the ignored index", () => {
    const output = written();
    const { spawn, calls } = prisma(
      { stdout: "-- empty\nLoaded Prisma config\n" },
      { stdout: 'DROP INDEX "ai"."chunk_embedding_idx";\n' },
    );
    expect(drift(spawn)).toBe(0);
    expect(calls).toEqual([
      "bunx prisma migrate diff --from-migrations prisma/migrations --to-schema prisma/schema --script",
      "bunx prisma migrate diff --from-config-datasource --to-schema prisma/schema --script",
    ]);
    expect(output()).toContain("No drift");
  });

  it("fails on any other statement, naming which side drifted", () => {
    const output = written();
    expect(drift(prisma({}, { stdout: 'ALTER TABLE "todo" ADD COLUMN "x" TEXT;' }).spawn)).toBe(1);
    expect(output()).toContain('Drift (database vs schema):\n  ALTER TABLE "todo"');
  });

  it("stops when prisma fails", () => {
    const output = written();
    expect(() => drift(prisma({ status: 1 }).spawn)).toThrow("prisma migrate diff failed");
    expect(output()).toContain("prisma failed");
  });
});

describe("apps/mobile's web build server", () => {
  const servers: { stop: (force?: boolean) => unknown }[] = [];
  afterEach(() => {
    for (const server of servers.splice(0)) {
      server.stop(true);
    }
  });

  /** A stand-in for the API or the web app: says what it was asked. */
  const upstream = (name: string) => {
    const server = Bun.serve({
      port: 0,
      async fetch(request) {
        const { pathname, search } = new URL(request.url);
        const body = await request.text();
        return Response.json(
          { name, method: request.method, path: pathname + search, body },
          { headers: { "x-upstream": name, connection: "keep-alive" } },
        );
      },
    });
    servers.push(server);
    return server.url.href;
  };

  /** A web build: index.html, an asset and a folder. */
  const build = () => {
    const dist = scratch();
    writeFileSync(join(dist, "index.html"), "<html>app</html>");
    writeFileSync(join(dist, "app.js"), "console.log(1)");
    mkdirSync(join(dist, "assets"));
    return dist;
  };

  it("needs its settings and a build", () => {
    const printed = captureOutput();
    expect(serveWeb({ API_URL: "x", WEB_URL: "y" }, build())).toBeNull();
    expect(printed()).toContain("MOBILE_WEB_PORT isn't set");
    const env = { MOBILE_WEB_PORT: "0", API_URL: "x", WEB_URL: "y" };
    expect(serveWeb(env, scratch())).toBeNull();
    expect(printed()).toContain("No web build");
  });

  it("serves the app, sends /rpc and /api to the API and the captcha page to the web app", async () => {
    const printed = captureOutput();
    const env = { MOBILE_WEB_PORT: "0", API_URL: upstream("api"), WEB_URL: upstream("web") };
    const server = serveWeb(env, build());
    if (!server) {
      throw new Error("the server didn't start");
    }
    servers.push(server);
    expect(printed()).toContain(`Mobile web build on http://localhost:${server.port}`);
    const get = (path: string, init?: RequestInit) => fetch(new URL(path, server.url), init);

    expect(await (await get("/healthz")).text()).toBe("ok");
    const rpc = await get("/rpc/todos?limit=2");
    expect(await rpc.json()).toEqual({
      name: "api",
      method: "GET",
      path: "/rpc/todos?limit=2",
      body: "",
    });
    expect(rpc.headers.get("x-upstream")).toBe("api");
    const posted = await get("/api/v1/todos", { method: "POST", body: '{"title":"a"}' });
    expect(await posted.json()).toMatchObject({ method: "POST", body: '{"title":"a"}' });
    expect(await (await get("/captcha")).json()).toMatchObject({ name: "web", path: "/captcha" });

    expect(await (await get("/app.js")).text()).toBe("console.log(1)");
    for (const path of ["/assets", "/settings/profile"]) {
      const page = await get(path);
      expect(page.headers.get("content-type")).toBe("text/html");
      expect(await page.text()).toBe("<html>app</html>");
    }
  });
});
